name: Docker Image CI

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t test .
    - uses: actions/checkout@v3
    - name: Run the Docker image
      run: |
        docker run test
        CONTAINER_ID=$(docker ps -alq)
        ls
        sudo docker cp $CONTAINER_ID:/spisok.pdf .
        ls -lh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Changed files
